---
# For use with pre-commit.
# See usage instructions at http://pre-commit.com

- id: ansible-lint
  name: Check ansible-lint
  description: This hook runs ansible-lint.
  entry: ansible-lint --force-color
  files: \.(yaml|yml)$
  language: python
  # do not pass files to ansible-lint, see:
  # https://github.com/ansible-community/ansible-lint/issues/611
  pass_filenames: false
  additional_dependencies:
    # https://github.com/pre-commit/pre-commit/issues/1526
    # if you want to use only the base ansible version for linting,
    # replace 'community' extra with 'core' or just mention the exact
    # version of Ansible you want to install as a dependency.
    - .[community,yamllint]

- id: yamllint
  entry: yamllint --strict
  files: \.(yaml|yml)$
  language: python
  types: [file, yaml]
...
