---
# Variable setup.
- name: Include OS-specific variables.
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"

- name: Define nginx_user.
  ansible.builtin.set_fact:
    nginx_user: "{{ __nginx_user }}"
  when: nginx_user is not defined

# Setup/install tasks.
- name: RedHat
  ansible.builtin.include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky'

- name: Ubuntu
  ansible.builtin.include_tasks: setup-Ubuntu.yml
  when: ansible_distribution == 'Ubuntu'

- name: Debian
  ansible.builtin.include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: FreeBSD
  ansible.builtin.include_tasks: setup-FreeBSD.yml
  when: ansible_os_family == 'FreeBSD'

- name: OpenBSD
  ansible.builtin.include_tasks: setup-OpenBSD.yml
  when: ansible_os_family == 'OpenBSD'

- name: Archlinux
  ansible.builtin.include_tasks: setup-Archlinux.yml
  when: ansible_os_family == 'Archlinux'

# Vhost configuration.
- name: vhosts
  ansible.builtin.import_tasks: vhosts.yml

# Nginx setup.
- name: Copy nginx configuration in place.
  ansible.builtin.template:
    src: "{{ nginx_conf_template }}"
    dest: "{{ nginx_conf_file_path }}"
    owner: root
    group: "{{ nginx_root_group }}"
    mode: 0644
  notify:
    - reload nginx

- name: Ensure nginx service is running as configured.
  ansible.builtin.service:
    name: nginx
    state: "{{ nginx_service_state }}"
    enabled: "{{ nginx_service_enabled }}"
...
