---
- name: restart nginx
  ansible.builtin.service:
    name: nginx
    state: restarted

- name: validate nginx configuration
  ansible.builtin.command:
    cmd: nginx -t -c /etc/nginx/nginx.conf
  changed_when: false

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: reloaded
...
