---
- name: Converge
  hosts: instance
  vars:
    nginx_use_ppa: true
    nginx_remove_default_vhost: true
    nginx_vhosts:
      - server_name: "pxe"
        root: "/var/www/html"
        listen: "8080"
        index: "index.html index.htm index.nginx-debian.html"
  pre_tasks:
    - name: Update apt cache.
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
      changed_when: false
  roles:
    - role: nginx
...
