---
- name: Verify
  hosts: instance
  tasks:
  - name: Populate service facts
    service_facts:
  - name: Assert that nginx.service is installed, enabled and running
    assert:
      that:
        - "'nginx.service' in ansible_facts.services"
        - "ansible_facts.services['nginx.service'].status == 'enabled'"
        - "ansible_facts.services['nginx.service'].state == 'running'"
  - name: Check if port 8080 is open
    wait_for:
      host: 0.0.0.0
      port: "8080"
      state: started
      delay: 0
      timeout: 3
  - name: Check if port 80 is closed
    wait_for:
      host: 0.0.0.0
      port: "80"
      state: stopped
      delay: 0
      timeout: 10

- name: External Verification
  hosts: verify
  gather_facts: false
  tasks:
    - name: Check that nginx works
      uri:
        url: http://instance:8080
...
