---
name: Develop

'on':
  push:
    branches:
      - develop
  workflow_dispatch:

jobs:
  ansible-linter:
    name: Ansible Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install ansible-lint Dependencies
        run: pip3 install ansible-lint

      - name: Lint Code Base with ansible-lint
        run: ansible-lint

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3

  yaml-linter:
    name: YAML Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install yamllint Dependencies
        run: pip3 install yamllint

      - name: Lint Code Base with yamllint
        run: yamllint .

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        MOLECULE_DISTRO:
          - ubuntu1804
          - ubuntu2004
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Molecule Dependencies
        run: pip install -r requirements.txt

      - name: Run Molecule Tests
        run: |
          for i in {1..3}; do
            molecule test --all && break
          done
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.MOLECULE_DISTRO }}

  pull-request:
    name: Pull Request
    runs-on: ubuntu-latest
    needs:
      - ansible-linter
      - pre-commit
      - yaml-linter
      - molecule
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          branch: main
          token: ${{ secrets.PAT }}

  notify:
    name: Slack Notifications
    runs-on: ubuntu-latest
    if: ${{ failure() }}
    needs:
      - pull-request
    steps:
      - name: Notify Slack channel on failure
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_ICON: https://github.com/ckaserer/logos/raw/master/ansible.png
          SLACK_USERNAME: ${{ github.repository }}
          SLACK_COLOR: '#ff0033'
          SLACK_FOOTER: ''
...
