---
name: CI

'on':
  push:
    branches: 
      - '**'
    tags-ignore:
      - '**'
  schedule:
    - cron: '30 8 * * 3'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

defaults:
  run:
    working-directory: gepaplexx.nginx

jobs:
  linter:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: gepaplexx.nginx

      - name: Lint Code Base
        uses: github/super-linter@v3
        env:
          VALIDATE_ALL_CODEBASE: true
          FILTER_REGEX_EXCLUDE: '.*.md'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2004
          - debian10
      fail-fast: false

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          path: gepaplexx.nginx

      - name: Set up Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: pip3 install -r requirements.txt

      - name: Run Molecule tests
        run: molecule test
        env:
          PY_COLORS: 1
          ANSIBLE_FORCE_COLOR: 1
          MOLECULE_DISTRO: ${{ matrix.distro }}

...